"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CAPACITOR_COOKIE_PROXY_SRC = exports.COOKIE_PROXY_SRC = exports.SWALLOW_API_SRC = exports.OLD_AGENT_SRC = exports.HTML_REQUIRED = exports.HTML_IDENTIFIER = exports.DEFAULT_SWALLOW_API_INJECTION = void 0;
exports.DEFAULT_SWALLOW_API_INJECTION = true;
exports.HTML_IDENTIFIER = ['ion-app', 'app-root'];
exports.HTML_REQUIRED = ['<html', '<head', '</head>', '</html>'];
exports.OLD_AGENT_SRC = 'assets/dtAgent.js';
exports.SWALLOW_API_SRC = 'assets/dtrum-swallow-api.js';
exports.COOKIE_PROXY_SRC = 'assets/dt-cookie-proxy.js';
exports.CAPACITOR_COOKIE_PROXY_SRC = 'assets/dt-cookie-proxy-cap.js';
