"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PLUGIN_UPDATE_RECOMMEND = exports.PLUGIN_UP_TO_DATE = exports.PLUGIN_LATEST = exports.PLUGIN_CURRENT = exports.MISSING_GRADLE = exports.MISSING_PLIST = exports.MISSING_DYNATRACE_CONFIG = exports.MISSING_IOS_DOMAIN_PROP = exports.MISSING_IOS_HYBRID_PROP = exports.MISSING_ANDROID_HYBRID_BLOCK = exports.MFP_VERSION_NOT_SUPPORTED = exports.GRADLE_VERSION_NOT_SUPPORTED = exports.JSAGENT_REQ = exports.MFP_REQ = exports.NATIVE_REQ = exports.SEE_RESOLUTION = exports.MORE_INFO = exports.NATIVE_MFP_REQUESTS_REQ = exports.NO_PROBLEMS = exports.NO_DEPENDENCIES = exports.PLATFORM_ANDROID = exports.PLATFORM_IOS = exports.DEPENDENCIES_HEADING = exports.IMPORTANT_HEADING = exports.PROBLEMS_REC_HEADING = exports.NATIVE_DEPENDENCIES_HEADING = exports.BUILD_FRAMEWORK_HEADING = exports.PLUGIN_VERSION_HEADING = exports.DOCTOR_DYNATRACE_HEADING = exports.NPM_CHANGELOG_DOC = exports.NPM_GRADLE_DOC = exports.NPM_IOS_CORR_ISSUES_DOC = exports.NPM_NATIVE_WR_DOC = exports.NPM_MFP_DOC = exports.NPM_CUSTOM_ARGS_DOC = exports.NPM_HYBRID_CONFIG = exports.NPM_DYNATRACE_CONFIG_DOC = exports.GRADLE_MIN_VERSION = exports.MFP_MIN_VERSION = exports.DEPENDENCY_LIST = exports.MFP_DEPENDENCY_NAME = exports.RESET = exports.REVERSE = exports.UNDERLINED = exports.BOLD = exports.BG_CYAN = exports.CYAN_FONT = exports.YELLOW_FONT = exports.GREEN_FONT = exports.RED_FONT = exports.STAR = exports.ALERT = exports.WARN = exports.TADA = exports.RED_X = exports.GREEN_CHECK = exports.DYNATRACE_NPM_PACKAGE_NAME = exports.NPM_PACKAGE_INFO_API = void 0;
exports.NPM_PACKAGE_INFO_API = "https://registry.npmjs.org/@dynatrace/cordova-plugin/latest";
exports.DYNATRACE_NPM_PACKAGE_NAME = "@dynatrace/cordova-plugin";
exports.GREEN_CHECK = "✅";
exports.RED_X = "❌";
exports.TADA = "🎉";
exports.WARN = "❗️";
exports.ALERT = "🚨";
exports.STAR = "⭐️";
exports.RED_FONT = "\x1b[31m";
exports.GREEN_FONT = "\x1b[32m";
exports.YELLOW_FONT = "\x1b[33m";
exports.CYAN_FONT = "\x1b[36m";
exports.BG_CYAN = "\x1b[46m";
exports.BOLD = "\u001B[1m";
exports.UNDERLINED = "\x1b[4m";
exports.REVERSE = "\x1b[7m";
exports.RESET = "\x1b[0m";
exports.MFP_DEPENDENCY_NAME = "cordova-plugin-mfp";
exports.DEPENDENCY_LIST = ['@ionic-native/http', 'cordova-plugin-advanced-http', exports.MFP_DEPENDENCY_NAME, 'cordova-plugin-okhttp'];
exports.MFP_MIN_VERSION = "8.0.0";
exports.GRADLE_MIN_VERSION = 5;
exports.NPM_DYNATRACE_CONFIG_DOC = exports.CYAN_FONT + "https://www.npmjs.com/package/@dynatrace/cordova-plugin#2-configuration-with-dynatrace" + exports.RESET + "\n";
exports.NPM_HYBRID_CONFIG = exports.CYAN_FONT + "https://www.npmjs.com/package/@dynatrace/cordova-plugin#hybrid-related-configuration" + exports.RESET + "\n";
exports.NPM_CUSTOM_ARGS_DOC = exports.CYAN_FONT + "https://www.npmjs.com/package/@dynatrace/cordova-plugin#3-make-a-build" + exports.RESET + "\n";
exports.NPM_MFP_DOC = exports.CYAN_FONT + "https://www.npmjs.com/package/@dynatrace/cordova-plugin#ibm-mobile-first" + exports.RESET + "\n";
exports.NPM_NATIVE_WR_DOC = exports.CYAN_FONT + "https://www.npmjs.com/package/@dynatrace/cordova-plugin#native-webrequests" + exports.RESET + "\n";
exports.NPM_IOS_CORR_ISSUES_DOC = exports.CYAN_FONT + "https://www.npmjs.com/package/@dynatrace/cordova-plugin#ios-session-correlation-issues" + exports.RESET + "\n";
exports.NPM_GRADLE_DOC = exports.CYAN_FONT + "https://www.npmjs.com/package/@dynatrace/cordova-plugin#updating-to-gradle-5" + exports.RESET + "\n";
exports.NPM_CHANGELOG_DOC = exports.CYAN_FONT + "https://www.npmjs.com/package/@dynatrace/cordova-plugin#changelog" + exports.RESET + "\n";
exports.DOCTOR_DYNATRACE_HEADING = "==================================\n| \uD83C\uDFE5 " + exports.UNDERLINED + exports.BOLD + "Doctor Dynatrace Results" + exports.RESET + " \uD83D\uDCF1 |\n==================================";
exports.PLUGIN_VERSION_HEADING = exports.BOLD + "----------------------------\n| Dynatrace Plugin Version |\n----------------------------" + exports.RESET;
exports.BUILD_FRAMEWORK_HEADING = exports.BOLD + "-------------------\n| Build Framework |\n-------------------" + exports.RESET;
exports.NATIVE_DEPENDENCIES_HEADING = exports.BOLD + "-----------------------------------\n| Native Web Request Dependencies |\n-----------------------------------" + exports.RESET;
exports.PROBLEMS_REC_HEADING = exports.BOLD + "---------------\n| " + exports.RED_X + " Problems |\n| " + exports.GREEN_CHECK + " Solution |\n---------------" + exports.RESET;
exports.IMPORTANT_HEADING = "\n\n" + exports.BOLD + "-------------------\n| " + exports.ALERT + exports.YELLOW_FONT + exports.BOLD + " IMPORTANT " + exports.RESET + exports.ALERT + exports.BOLD + " |\n-------------------" + exports.RESET + "\n";
exports.DEPENDENCIES_HEADING = exports.BOLD + "--------------------\n| All dependencies |\n--------------------" + exports.RESET;
exports.PLATFORM_IOS = "iOS";
exports.PLATFORM_ANDROID = "Android";
exports.NO_DEPENDENCIES = "None found";
exports.NO_PROBLEMS = "\n" + exports.TADA + exports.GREEN_FONT + exports.BOLD + " No problems found! " + exports.RESET + exports.TADA + "\n";
exports.NATIVE_MFP_REQUESTS_REQ = "will require an instrumented webserver with version " + exports.GREEN_FONT + exports.BOLD + ">= 1.211.x." + exports.RESET;
exports.MORE_INFO = "\n" + exports.GREEN_FONT + exports.BOLD + "More info:" + exports.RESET;
exports.SEE_RESOLUTION = "\n\n" + exports.GREEN_FONT + exports.BOLD + "Fix:" + exports.RESET;
exports.NATIVE_REQ = "\nUsing the Native WebRequests feature " + exports.NATIVE_MFP_REQUESTS_REQ + "\n" + exports.MORE_INFO + "\n" + exports.NPM_NATIVE_WR_DOC + "\n";
exports.MFP_REQ = "\nUsing the IBM Mobile First feature " + exports.NATIVE_MFP_REQUESTS_REQ + "\n" + exports.MORE_INFO + "\n" + exports.NPM_MFP_DOC + "\n";
exports.JSAGENT_REQ = "\nWhen using capacitor/ionic with iOS, to ensure the Mobile and Web sessions correlate properly, version " + exports.GREEN_FONT + exports.BOLD + "1.219+" + exports.RESET + " of the JavaScript agent is required!\n" + exports.MORE_INFO + "\n" + exports.NPM_IOS_CORR_ISSUES_DOC;
exports.GRADLE_VERSION_NOT_SUPPORTED = "\n" + exports.RED_X + " Android Gradle version " + exports.RED_FONT + exports.BOLD + "< 5 is not supported." + exports.RESET + "\n--> " + exports.GREEN_CHECK + " Please update your Android gradle to version " + exports.GREEN_FONT + exports.BOLD + ">= 5.x.x." + exports.RESET + "\n\n\t" + exports.NPM_GRADLE_DOC;
exports.MFP_VERSION_NOT_SUPPORTED = "\n" + exports.RED_X + " IBM Mobile First version " + exports.RED_FONT + exports.BOLD + "< 8.x.x is not supported." + exports.RESET + "\n--> " + exports.GREEN_CHECK + " Please update to version " + exports.GREEN_FONT + exports.BOLD + ">= 8.x.x" + exports.RESET + " to use this feature.";
exports.MISSING_ANDROID_HYBRID_BLOCK = "\n" + exports.RED_X + " Missing the Android hybridWebView block in the dynatrace.config.js file.\n--> " + exports.GREEN_CHECK + " Add the hybridWebView block in the dynatrace.config.js file.\n\n\t" + exports.NPM_HYBRID_CONFIG;
exports.MISSING_IOS_HYBRID_PROP = "\n" + exports.RED_X + " Missing the iOS DTXHybridApplication property in the dynatrace.config.js file.\n--> " + exports.GREEN_CHECK + " Update your dynatrace.config.js file to include the DTXHybridApplication property.\n\n\t" + exports.NPM_HYBRID_CONFIG;
exports.MISSING_IOS_DOMAIN_PROP = "\n" + exports.RED_X + " Missing the iOS DTXSetCookiesForDomain property in the dynatrace.config.js file.\n--> " + exports.GREEN_CHECK + " Add the DTXSetCookiesForDomain property with your desired domains to your dynatrace.config.js file.\n\n\t" + exports.NPM_HYBRID_CONFIG;
exports.MISSING_DYNATRACE_CONFIG = "\n" + exports.RED_X + " Unable to find the dynatrace.config.js file in root directory.\n--> " + exports.GREEN_CHECK + " If using a dynatrace.config.js file in a different location than the root directory, please use the custom CLI parameter --config=<locationOfConfig>\n\n\t" + exports.NPM_DYNATRACE_CONFIG_DOC;
exports.MISSING_PLIST = "\n" + exports.RED_X + " Unable to find Info.plist.\n--> " + exports.GREEN_CHECK + " If using a plist in a different location than the project's default, please use the custom CLI parameter --plist=<locationOfPlist>\n\n\t" + exports.NPM_DYNATRACE_CONFIG_DOC;
exports.MISSING_GRADLE = "\n" + exports.RED_X + " Unable to find top-level build.gradle.\n--> " + exports.GREEN_CHECK + " If using a gradle file in a different location than the project's default, please use the custom CLI parameter --gradle=<locationOfTopLevel-build.gradle>\n\n\t" + exports.NPM_DYNATRACE_CONFIG_DOC;
exports.PLUGIN_CURRENT = "Current: ";
exports.PLUGIN_LATEST = "Latest: ";
exports.PLUGIN_UP_TO_DATE = "\n" + exports.TADA + exports.GREEN_FONT + exports.BOLD + " Up to date! " + exports.RESET + exports.TADA + "\n";
exports.PLUGIN_UPDATE_RECOMMEND = "\n" + exports.STAR + exports.BOLD + exports.GREEN_FONT + " A newer plugin version is available! " + exports.RESET + exports.STAR + "\n\nPlease see our changelog and update for our latest features and bugfixes.\n--> " + exports.NPM_CHANGELOG_DOC;
